language: ruby
rvm:
  - 2.2.3
  
cache: 
  - bundler
  - apt

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml

git:
  depth: 3

bundler_args: --without production
